my_name: ДОЛ Бауманец | Радист

my_commands:
  help: Получить помощь

help_markdown: |
  Я - бот радист ДОЛ "Бауманец"

  Пришли мне музыку и я помогу запустить её на калакольчиках

audio_reply:
  run_immediately: 🚀 Запустить немедленно

stop_play: ⛔ Остановить